# This is a basic workflow to help you get started with Actions

name: Sync Thunderbird

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: mirror ttps://hg.mozilla.org/comm-central
        uses: 'mozillazg/mirror-hg-repo@v2'
        with:
          source-hg-repo-url: 'https://hg.mozilla.org/comm-central'
          destination-git-repo-owner: 'Summpot'
          destination-git-repo-name: 'thunderbird'
          destination-git-personal-token: '${{ secrets.PAT }}'
          force-push: true
